{% set name = "crcmod" %}
{% set version = "1.7" %}

package:
    name: '{{ name|lower }}'
    version: '{{ version }}'

source:
    fn: '{{ name }}-{{ version }}.tar.gz'
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: dc7051a0db5f2bd48665a990d3ec1cc305a466a77358ca4492826f41f283601e

build:
    noarch: python
    number: 1
    script: "python -m pip install --no-deps --ignore-installed ."

requirements:
    host:
        - python
        - pip
    run:
        - python

test:
    imports:
        - crcmod

about:
    home: http://crcmod.sourceforge.net
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: CRC Generator
    description: "Python module for generating objects that compute the Cyclic Redundancy Check (CRC)"

extra:
    recipe-maintainers:
        - bgruening
        - chapmanb
